EOS-20069: s3 audit log schema json fix
Seagate/cortx-s3server pull request #1021
Opened 2021-07-06 05:57 UTC by SaumitraK531

Signed-off-by: Saumitra Kulkarni saumitra.kulkarni@seagate.com

2021-07-06 05:58 UTC, bkirunge7 approved these changes

2021-07-06 06:13 UTC, kupranay requested changes
Its very difficult and not maintainable to understand this json.
Please format it properly

[{
	"field_id": "authentication_type",
	"label": "Authentication Type",
	"display_id": 101,
	"display": true,
	"sortable": true,
	"filterable": false
}, {
	"field_id": "bucket",
	"label": "Bucket",
	"display_id": 102,
	"display": true,
	"sortable": true,
	"filterable": false
}, {
	"field_id": "bucket_owner",
	"label": "Bucket Owner",
	"display_id": 103,
	"display": false,
	"sortable": true,
	"filterable": false
}, {
	"field_id": "bytes_received",
	"label": "Bytes Received",
	"display_id": 104,
	"display": true,
	"sortable": true,
	"filterable": false
}, {
	"field_id": "bytes_sent",
	"label": "Bytes_Sent",
	"display_id": 105,
	"display": true,
	"sortable": true,
	"filterable": false
}, {
	"field_id": "cipher_suite",
	"label": "Cipher_Suite",
	"display_id": 106,
	"display": true,
	"sortable": true,
	"filterable": false
}, {
	"field_id": "error_code",
	"label": "Error Code",
	"display_id": 107,
	"display": true,
	"sortable": true,
	"filterable": false
}, {
	"field_id": "host_header",
	"label": "Host Header",
	"display_id": 108,
	"display": true,
	"sortable": true,
	"filterable": false
}, {
	"field_id": "host_id",
	"label": "Host Id",
	"display_id": 109,
	"display": true,
	"sortable": true,
	"filterable": false
}, {
	"field_id": "http_status",
	"label": "Http Status",
	"display_id": 110,
	"display": true,
	"sortable": true,
	"filterable": false
}, {
	"field_id": "object_size",
	"label": "Object Size",
	"display_id": 111,
	"display": true,
	"sortable": true,
	"filterable": false
}, {
	"field_id": "operation",
	"label": "Operation",
	"display_id": 112,
	"display": true,
	"sortable": true,
	"filterable": false
}, {
	"field_id": "referrer",
	"label": "Referer",
	"display_id": 113,
	"display": true,
	"sortable": true,
	"filterable": false
}, {
	"field_id": "remote_ip",
	"label": "Remote Ip",
	"display_id": 114,
	"display": true,
	"sortable": true,
	"filterable": false
}, {
	"field_id": "request_id",
	"label": "Request Id",
	"display_id": 115,
	"display": true,
	"sortable": true,
	"filterable": false
}, {
	"field_id": "request_uri",
	"label": "Request Uri",
	"display_id": 116,
	"display": true,
	"sortable": true,
	"filterable": false
}, {
	"field_id": "requester",
	"label": "Requester",
	"display_id": 117,
	"display": true,
	"sortable": true,
	"filterable": false
}, {
	"field_id": "signature_version",
	"label": "Signature Version",
	"display_id": 118,
	"display": true,
	"sortable": true,
	"filterable": false
}, {
	"field_id": "timestamp",
	"label": "Timestamp",
	"display_id": 119,
	"sortable": true,
	"filterable": true,
	"display": true,
	"value": {
		"type": "date"
	}
}, {
	"field_id": "time",
	"label": "Time",
	"display_id": 120,
	"display": true,
	"sortable": true,
	"filterable": false
}, {
	"field_id": "total_time",
	"label": "Total Time",
	"display_id": 121,
	"display": true,
	"sortable": true,
	"filterable": false
}, {
	"field_id": "turn_around_time",
	"label": "Turn Around Time",
	"display_id": 122,
	"display": true,
	"sortable": true,
	"filterable": false
}, {
	"field_id": "user_agent",
	"label": "User Agent",
	"display_id": 123,
	"display": true,
	"sortable": true,
	"filterable": false
}, {
	"field_id": "version_id",
	"label": "Version Id",
	"display_id": 124,
	"display": true,
	"sortable": true,
	"filterable": false
}]


You can take help from jsonlint.com

2021-07-06 06:52 UTC, kupranay approved these changes

2021-07-07 02:40 UTC, SaumitraK531 commented
Mini-Provisioning Job: http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Mini-Provisioning/job/cortx-s3server/1487/
Status: Success

Pre-Merge: http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Component-Test/job/S3Server-PreMerge-Test/1737/
Status: Success

2021-07-07 05:18 UTC, nileshgovande commented
Cortx provisioning - http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/S3Server/930/

2021-07-07 10:38 UTC, merged