EOS-25891: Single PUT request to allow until 5GB
Seagate/cortx-s3server pull request #1602
Opened 2021-11-17 12:00 UTC by knrajnambiar76

Signed-off-by: Rajesh Nambiar <rajesh.nambiar@seagate.com>

# Problem Statement
- Problem statement

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

2021-11-17 13:13 UTC, pranavPawar07 approved these changes

2021-11-17 16:22 UTC, t7ko-seagate requested changes

2021-11-17 16:22 UTC, t7ko-seagate commented on server/s3_put_multiobject_action.cc
> +  } else if (request->get_content_length() >= MAXIMUM_ALLOWED_PUT_SIZE) {
Same as above -- we nay need to use `>`, not `>=`.

2021-11-22 07:44 UTC, t7ko-seagate approved these changes

2021-11-22 07:51 UTC, t7ko-seagate commented
Merging.  All jobs passed except for Codacy (which generated false positive on ut/ folder).

2021-11-22 07:51 UTC, merged