EOS-25627: Handle parallel multipart POST complete and Put part operations
Seagate/cortx-s3server pull request #1622
Opened 2021-11-25 15:55 UTC by DPG17

Signed-off-by: Dattaprasad Govekar <dattaprasad.govekar@seagate.com>

# Problem Statement
-  Parallel operations lead to object/index leak

# Design
-  Handling object leak due to parallel S3 operations (POST complete, multipart PUT, simple PUT)

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

2021-12-03 08:40 UTC, SeagateChaDeepak approved these changes
+1 LGTM

2021-12-06 11:52 UTC, t7ko-seagate requested changes

2021-12-06 12:01 UTC, DPG17 commented on s3backgrounddelete/s3backgrounddelete/object_recovery_validator.py
> +                extended_key = extended_key_prefix + str(part) + "|" + "F1"
S3server, as of now, does not support fragmentation within simple object (which is S3 fault tolerance feature's capability).
Once we have such feature in S3, we would have appropriate changes here.

2021-12-06 12:03 UTC, DPG17 commented on s3backgrounddelete/s3backgrounddelete/object_recovery_validator.py
> +            part_no = self.object_leak_info["part"]
ok

2021-12-07 06:19 UTC, t7ko-seagate approved these changes

2021-12-07 07:58 UTC, t7ko-seagate commented
Merging as per the team agreement that Codacy warnings can be ignored.

2021-12-07 07:58 UTC, merged