EOS-16890:Support for get_all_keys
Seagate/cortx-s3server pull request #675
Opened 2021-02-07 11:26 UTC by AtitaShirwaikar

Cortx-Utils had support for get_keys() which lists all the key-value pairs in a file.
Hooked up the support in s3confstore for get_keys API

Testing:
[root@ssc-vm-c-1632 cortx-s3server]# s3confstore yaml:///opt/seagate/cortx/s3/s3backgrounddelete/config.yaml getallkeys

['version_config>version', 'cortx_s3>endpoint', 'cortx_s3>service', 'cortx_s3>default_region', 'cortx_s3>daemon_mode', 'cortx_s3>s3_instance_count', 'cortx_s3>messaging_platform', 'message_bus>topic', 'message_bus>consumer_group', 'message_bus>consumer_id_prefix', 'message_bus>producer_id', 'message_bus>producer_delivery_mechanism', 'message_bus>consumer_sleep', 'logconfig>scheduler_logger_name', 'logconfig>processor_logger_name', 'logconfig>logger_directory', 'logconfig>scheduler_log_file', 'logconfig>processor_log_file', 'logconfig>file_log_level', 'logconfig>console_log_level', 'logconfig>log_format', 'logconfig>max_bytes', 'logconfig>backup_count', 'rabbitmq>username', 'rabbitmq>password', 'rabbitmq>host', 'rabbitmq>queue', 'rabbitmq>exchange', 'rabbitmq>exchange_type', 'rabbitmq>mode', 'rabbitmq>durable', 'rabbitmq>schedule_interval_secs', 'indexid>probable_delete_index_id', 'indexid>global_instance_index_id', 'indexid>global_bucket_index_id', 'indexid>bucket_metadata_index_id', 'indexid>max_keys', 'leakconfig>leak_processing_delay_in_mins', 'leakconfig>version_processing_delay_in_mins', 'leakconfig>cleanup_enabled']

2021-02-08 10:48 UTC, nileshgovande approved these changes

2021-02-08 10:49 UTC, vimalraghwani20 approved these changes

2021-02-08 10:57 UTC, amitwac2608 requested changes

2021-02-08 10:57 UTC, amitwac2608 commented on s3cortxutils/s3confstore/s3confstore/cortx_s3_confstore.py
> +  def get_all_keys(self):
Please write UT for this function

2021-02-08 13:55 UTC, gowthamchinna commented
run mini-provisioning

2021-02-08 17:59 UTC, AtitaShirwaikar commented on s3cortxutils/s3confstore/s3confstore/cortx_s3_confstore.py
> +  def get_all_keys(self):
done

2021-02-09 11:01 UTC, nileshgovande commented
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/S3server-7.8.2003/620/

2021-02-09 13:11 UTC, nileshgovande commented
MIni provisioning passed http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Mini-Provisioning/job/cortx-s3server/216/
Pre - merge #620 also passed. Merging

2021-02-09 13:11 UTC, merged